const SET_PATH2 = 'SET_PATH2';
const SET_HUNTER_DIRECTION2 = 'SET_GHOST_DIRECTION2';
const SET_HUNTER_POSITION2 = 'SET_HUNTER_POSITION2';
const SET_HUNTER_POSITION_FROM_HISTORY2 = 'SET_HUNTER_POSITION_FROM_HISTORY2';
const SAVE_HUNTER2 = 'SAVE_HUNTER2';
const KILL_HUNTER2 = 'KILL_HUNTER2';