const SET_PATH = 'SET_PATH';
const SET_HUNTER_DIRECTION = 'SET_GHOST_DIRECTION';
const SET_HUNTER_POSITION = 'SET_HUNTER_POSITION';
const SET_HUNTER_POSITION_FROM_HISTORY = 'SET_HUNTER_POSITION_FROM_HISTORY';
const SAVE_HUNTER = 'SAVE_HUNTER';