const SET_PATH3 = 'SET_PATH3';
const SET_HUNTER_DIRECTION3 = 'SET_GHOST_DIRECTION3';
const SET_HUNTER_POSITION3 = 'SET_HUNTER_POSITION3';
const SET_HUNTER_POSITION_FROM_HISTORY3 = 'SET_HUNTER_POSITION_FROM_HISTORY3';
const SAVE_HUNTER3 = 'SAVE_HUNTER3';
const KILL_HUNTER3 = 'KILL_HUNTER3';