const SWIPEUP = 'SWIPEUP';
const SWIPEDOWN = 'SWIPEDOWN';
const SWIPELEFT = 'SWIPELEFT';
const SWIPERIGHT = 'SWIPERIGHT';
const SET_DIRECTION = 'SET_DIRECTION';
const RESET_DIRECTION = 'RESET_DIRECTION';