const SWIPEUP = 'SWIPEUP';
const SWIPEDOWN = 'SWIPEDOWN';
const SWIPELEFT = 'SWIPELEFT';
const SWIPERIGHT = 'SWIPERIGHT';
const SET_PLAYER_DIRECTION = 'SET_PLAYER_DIRECTION';
const SET_PLAYER_POSITION = 'SET_PLAYER_POSITION';
const SET_PLAYER_POSITION_FROM_HISTORY = 'SET_PLAYER_POSITION_FROM_HISTORY';
const RESET_DIRECTION = 'RESET_DIRECTION';